
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DoubleTortureRackAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {19117, 2, 2, 0}, {19105, 1, 2, 0}, {19104, 0, 2, 0}// 1	2	3	
			, {19116, -1, 2, 0}, {19114, -1, 1, 0}, {19106, -1, 0, 0}// 4	5	6	
			, {19107, -1, -1, 0}, {19115, 0, -1, 10}// 7	8	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DoubleTortureRackAddonDeed();
			}
		}

		[ Constructable ]
		public DoubleTortureRackAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public DoubleTortureRackAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DoubleTortureRackAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DoubleTortureRackAddon();
			}
		}

		[Constructable]
		public DoubleTortureRackAddonDeed()
		{
			Name = "DoubleTortureRack";
		}

		public DoubleTortureRackAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}