
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class StarTableAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {11840, 2, 0, 0}, {11840, 1, 0, 0}, {11841, 3, 3, 0}// 13	14	15	
			, {11841, 3, 2, 0}, {11843, 3, 1, 0}, {11844, 3, 0, 0}// 16	17	18	
			, {11844, 3, -1, 0}, {11843, 3, -2, 0}, {11843, 2, 3, 0}// 19	20	21	
			, {11842, 2, 2, 0}, {11843, 2, 1, 0}, {11841, 2, -1, 0}// 22	23	24	
			, {11842, 2, -2, 0}, {11841, 1, 3, 0}, {11845, 1, 2, 0}// 25	26	27	
			, {11844, 1, 1, 0}, {11843, 1, -1, 0}, {11844, 1, -2, 0}// 28	29	30	
			, {11843, 0, 3, 0}, {11844, 0, 2, 0}, {11843, 0, 1, 0}// 31	32	33	
			, {11843, 0, 0, 0}, {11842, 0, -1, 0}, {11845, 0, -2, 0}// 34	35	36	
			, {11845, -1, 3, 0}, {11841, -1, 2, 0}, {11845, -1, 1, 0}// 37	38	39	
			, {11843, -1, 0, 0}, {11843, -1, -1, 0}, {11843, -1, -2, 0}// 40	41	42	
			, {11841, -2, 3, 0}, {11842, -2, 2, 0}, {11842, -2, 1, 0}// 43	44	45	
			, {11842, -2, 0, 0}, {11844, -2, -1, 0}, {11842, -2, -2, 0}// 46	47	48	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new StarTableAddonDeed();
			}
		}

		[ Constructable ]
		public StarTableAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2602, 1, -1, 0, 1954, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2602, 0, -1, 0, 1954, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2602, -1, 0, 0, 1954, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2602, -1, 1, 0, 1954, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2602, 2, 0, 0, 1954, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2602, 2, 1, 0, 1954, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2602, 1, 2, 0, 1954, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2602, 0, 2, 0, 1954, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2879, 1, 1, 0, 1954, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 2879, 1, 0, 0, 1954, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 2879, 0, 1, 0, 1954, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2879, 0, 0, 0, 1954, -1, "", 1);// 12

		}

		public StarTableAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class StarTableAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new StarTableAddon();
			}
		}

		[Constructable]
		public StarTableAddonDeed()
		{
			Name = "StarTable";
		}

		public StarTableAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}